# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_imports = true

# Be reasomably compact
enum_discrim_align_threshold = 50
fn_single_line = true
max_width = 90
use_field_init_shorthand = true
use_small_heuristics = "Max"

# Be consistent
reorder_impl_items = true
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

# Work around https://github.com/rust-lang/rustfmt/issues/3149
edition = "2021"
