#!/bin/sh
#
# Deploy to Netlify - commit artefacts to a clean branch, and force-push to GitHub

# Check for running trunk, which can mess up git when switching branches
if ps x | grep 'trun[k]' > /dev/null; then
  echo !!! Trunk watcher running - please kill it first !!!
  exit 1
fi

# Create a clean `deploy` branch
git branch -D deploy
git checkout -b deploy

# Build the production assets
echo Building...
rm -rf dist
trunk build --release

# Push to GitHub
echo Pushing...
git add -f dist/*
git commit -a -m "Automated deploy script"
git push git@github.com:simonchatts/names deploy --force

# Restore dev environment
git checkout main
echo Done
